name: Validate Architecture Markdown

on:
  push:
    paths:
      - architecture.md
  pull_request:
    paths:
      - architecture.md

jobs:
  validate-architecture-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate architecture.md
        run: |
          FILE="architecture.md"

          # Check if the file exists
          if [ ! -f "$FILE" ]; then
            echo "❌ architecture.md not found!"
            exit 1
          fi

          # Check for Mermaid diagram
          if ! grep -q '```mermaid' "$FILE"; then
            echo "❌ Mermaid diagram not found in architecture.md"
            exit 1
          fi

          # Check for footnote reference
          if ! grep -q '\[\^compliance-hc\]' "$FILE"; then
            echo "❌ Footnote [^compliance-hc] missing"
            exit 1
          fi

          # Check for inline deployment command
          if ! grep -q 'uv deploy' "$FILE"; then
            echo "❌ Inline deployment command missing"
            exit 1
          fi

          echo "✅ architecture.md passed all checks"
